FROM nvcr.io/nvidia/tritonserver:23.01-py3
# https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
# Please choose previous tritonserver:xx.xx if you encounter cuda driver mismatch issue

LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

RUN apt-get update  && apt-get -y install \
    python3-dev \
    cmake \
    libsndfile1

# 安装对应的包结果
RUN pip3 install torch==2.1.0+cu118 torchaudio==2.1.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html

# 安装kaldifeat版本
COPY kaldifeat-1.25.3.dev20231221+cuda11.8.torch2.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64  kaldifeat-1.25.3.dev20231221+cuda11.8.torch2.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64
# RUN pip3 install kaldifeat==1.25.3.dev20231221+cuda11.7.torch2.0.1 -f https://csukuangfj.github.io/kaldifeat/cuda.html
RUN pip3 install ./kaldifeat-1.25.3.dev20231221+cuda11.8.torch2.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64

# 安装服务依赖的包
RUN pip3 install pyyaml -i https://pypi.tuna.tsinghua.edu.cn/simple

# 安装client依赖的包
RUN pip3 install soundfile grpcio-tools tritonclient -i https://pypi.tuna.tsinghua.edu.cn/simple
WORKDIR /workspace